tasks:
  - name: install go & aws cli
    init: |
      echo init
      
    command: |
      echo command
      sudo apt -y install golang
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      clear
      go get && go build ./... && go test ./...
      go run .
      
vscode:
  extensions:
    - golang.Go